### ISSUE TITLE
Add an api route for posting new messages

### ISSUE THREAD

**Issue by psitronic** [Otto-AA/Tag_server#8]
The route should receive the message text, url, and username to whom it is addressed, and store in db

**Comment by Otto-AA** [comment]
As I already mentionend, I would prefer to work with something like `recpients: "friends"` instead of `createdFor: ["user1", "user3", "user4", ...]` as this seems easier to extend and better at scaling (regarding the storage, not the performance)

Anyway I think that the client side should only send the recipent target (friends / group / ?) and server side should find out the individual userIds.  (In case of `createdFor` this then would happen before saving it to the database, in case of `recipient` it would happen after retrieving it from the database and before sending it to the user)

**Comment by Otto-AA** [comment]
Regarding the url, maybe we should double check it with the [referer header](https://stackoverflow.com/q/11875522/6548154). But as this header isn't send with all requests we can't fully rely on it, only checking for some cases :/

**Comment by okramovic** [comment]
i also agree with having recipient of message as short as possible, eg: public/ friends /private instead of repeating all persons friends in every message he posts

**Comment by psitronic** [comment]
In this case, we need to create one more collection, say, friends.

**Comment by Otto-AA** [comment]
What about the friends defined in user?

**Comment by psitronic** [comment]
We should avoid a mess in db. It should be well structured. If we have friends in the users collection, then we need to add also e.g. groups to the users collection and linked all these things. Then it will be not understandable.

**Comment by Otto-AA** [comment]
If we later would add groups, I would store them in a separate collection. 

So if a request comes we can switch depending on the specified recipient:
- case friends: get friends from user collection
- case group: get users of group

and go on with this list of userIds to get the messages.

But if you think storing both friends and later groups in their collection we can do that as well. It doesn't looks like a significant difference to me.
